# Generated by Django 5.2.4 on 2025-07-16 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('custo', models.JSONField(default=dict)),
                ('tipo', models.CharField(choices=[('AR', 'Arremesso'), ('CU', 'Curta'), ('DE', 'Desarmado'), ('LO', 'Longa'), ('PE', 'Pesada'), ('PR', 'Projetil'), ('UM', 'Uma Mão'), ('ES', 'Escudo'), ('AN', 'Antídoto'), ('VE', 'Veneno'), ('LE', 'Leve'), ('ME', 'Média'), ('CO', 'Comum')], default='CO', max_length=2)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtefatoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao_geral', models.TextField()),
                ('tipo', models.CharField(choices=[('H', 'Habilidade'), ('T', 'Traço'), ('P', 'Poder Místico')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Qualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo', models.CharField(choices=[('JOGADOR', 'Jogador'), ('MESTRE', 'Mestre'), ('ADMIN', 'Administrador')], default='JOGADOR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('equipamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.equipamento')),
            ],
            bases=('api.equipamento',),
        ),
        migrations.CreateModel(
            name='Armadura',
            fields=[
                ('equipamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.equipamento')),
            ],
            bases=('api.equipamento',),
        ),
        migrations.CreateModel(
            name='Elixir',
            fields=[
                ('equipamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.equipamento')),
                ('efeito', models.TextField()),
            ],
            bases=('api.equipamento',),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='equipamento_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='api.equipamentobase'),
        ),
        migrations.CreateModel(
            name='Aprende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('N', 'Novato'), ('A', 'Adepto'), ('M', 'Mestre')], default='N', max_length=1)),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habilidade')),
            ],
        ),
        migrations.CreateModel(
            name='JogadorPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('fotoDePerfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_jogador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField(default=18)),
                ('experiencia', models.PositiveIntegerField(default=0)),
                ('experiencia_nao_gasta', models.PositiveIntegerField(default=0)),
                ('raca', models.CharField(choices=[('HA', 'Humano Ambriano'), ('HB', 'Humano Bárbaro'), ('CA', 'Cambiante'), ('GO', 'Goblin'), ('OG', 'Ogro'), ('EL', 'Elfo'), ('AN', 'Anão'), ('HS', 'Humano Sequestrado'), ('TR', 'Troll'), ('MV', 'Morto-vivo')], default='HA', max_length=2)),
                ('ocupacao', models.CharField(blank=True, max_length=100, null=True)),
                ('vitaliade_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('vitalidade_atual', models.PositiveIntegerField(blank=True, null=True)),
                ('limiar_de_dor', models.PositiveIntegerField(blank=True, null=True)),
                ('corrupcao_permanente', models.PositiveIntegerField(default=0)),
                ('corrupcao_temporaria', models.PositiveIntegerField(default=0)),
                ('limiar_de_corrupcao', models.PositiveIntegerField(blank=True, null=True)),
                ('sombra', models.CharField(blank=True, max_length=100, null=True)),
                ('citacao', models.CharField(blank=True, max_length=200, null=True)),
                ('astuto', models.PositiveBigIntegerField(default=10)),
                ('discreto', models.PositiveBigIntegerField(default=10)),
                ('persuasivo', models.PositiveBigIntegerField(default=10)),
                ('preciso', models.PositiveBigIntegerField(default=10)),
                ('rapido', models.PositiveBigIntegerField(default=10)),
                ('resoluto', models.PositiveBigIntegerField(default=10)),
                ('vigilante', models.PositiveBigIntegerField(default=10)),
                ('vigoroso', models.PositiveBigIntegerField(default=10)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aparencia', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_personagens/')),
                ('historico', models.TextField(blank=True, null=True)),
                ('objetivo_pessoal', models.TextField(blank=True, null=True)),
                ('amigos_e_companheiros', models.TextField(blank=True, null=True)),
                ('dinheiro', models.JSONField(default=dict)),
                ('outras_riquezas', models.TextField(blank=True, null=True)),
                ('habilidades_e_poderes', models.ManyToManyField(related_name='personagens', through='api.Aprende', to='api.habilidade')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to='api.jogadorperfil')),
                ('armas_equipadas', models.ManyToManyField(blank=True, related_name='personagem_empunhando', to='api.arma')),
                ('armadura_equipada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personagem_vestindo', to='api.armadura')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='personagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='api.personagem'),
        ),
        migrations.CreateModel(
            name='Artefato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipado', models.BooleanField(default=False)),
                ('artefato_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artefatos', to='api.artefatobase')),
                ('personagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artefatos', to='api.personagem')),
            ],
        ),
        migrations.AddField(
            model_name='aprende',
            name='personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personagem'),
        ),
        migrations.CreateModel(
            name='Poder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('requesito', models.TextField()),
                ('descricao', models.TextField()),
                ('acao', models.CharField(choices=[('A', 'Ativa'), ('L', 'Livre'), ('P', 'Passiva'), ('R', 'Reação'), ('E', 'Especial')], default='A', max_length=1)),
                ('corrupcao', models.CharField(max_length=50)),
                ('artefato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poderes', to='api.artefato')),
            ],
        ),
        migrations.CreateModel(
            name='ArmaBase',
            fields=[
                ('equipamentobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.equipamentobase')),
                ('dano', models.CharField(max_length=50)),
                ('qualidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armas_base', to='api.qualidade')),
            ],
            bases=('api.equipamentobase',),
        ),
        migrations.AddField(
            model_name='arma',
            name='arma_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armas', to='api.armabase'),
        ),
        migrations.CreateModel(
            name='ArmaduraBase',
            fields=[
                ('equipamentobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.equipamentobase')),
                ('protecao', models.CharField(max_length=50)),
                ('qualidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armaduras_base', to='api.qualidade')),
            ],
            bases=('api.equipamentobase',),
        ),
        migrations.AddField(
            model_name='armadura',
            name='armadura_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armaduras', to='api.armadurabase'),
        ),
        migrations.CreateModel(
            name='DescricaoHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_habilidade', models.CharField(choices=[('N', 'Novato'), ('A', 'Adepto'), ('M', 'Mestre')], default='N', max_length=1)),
                ('tipo_acao', models.CharField(choices=[('A', 'Ativa'), ('L', 'Livre'), ('P', 'Passiva'), ('R', 'Reação'), ('E', 'Especial')], default='A', max_length=1)),
                ('descricao', models.TextField()),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descricoes', to='api.habilidade')),
            ],
            options={
                'unique_together': {('habilidade', 'nivel_habilidade')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='aprende',
            unique_together={('personagem', 'habilidade')},
        ),
    ]
